[tool.pytest.ini_options]
minversion = "6.0"
xfail_strict=true
addopts = [
    "-vv",
    "--color=yes",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "W"]
ignore-init-module-imports = true

[tool.ruff.extend-per-file-ignores]
"docs/conf.py" = ["E501"]
"tests/test_*.py" = ["F841"]

[tool.coverage.report]
exclude_lines = [
  "pragma: nocover",
  "raise NotImplementedError",
  "if TYPE_CHECKING:",
]

[tool.nbqa.mutate]
isort = 1
black = 1
pyupgrade = 1
